### ISSUE TITLE
No scores/mapvote at the end of some custom maps

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#2] opened 2023-01-20 17:34 UTC
Hello

At the end of some custom maps, the scores and the mapvote doesn't appear, but the game directly loads next map.
MiscModversion = 3.0.9 (server being set up using cod.pm, I'm using codextended v20)

Does someone thinks where the issue could come from ?

Here are maps where the problem occurs :
- https://vcodmods.com/view/wawa_3daim
- https://vcodmods.com/view/zh_highrise-by-zilch

Here are maps where the problem doesn't occurs :
- https://vcodmods.com/view/sainteny
- https://vcodmods.com/view/german_town
_____________________

Please help me

**Comment by cato-a** [comment] 2023-01-20 18:11
Hello, what you describe sounds like an issue with the server setup/config. It's difficult to guess without knowing how everything is setup and if you use any other mods. Other mods are likely the reason for the problem.

And this is probably the reason for #3 as well.

**Comment by cato-a** [comment] 2023-01-20 22:32
After much troubleshooting this comes down to a problem with CoDaM and missing intermission spawnpoints on some maps. Not a bug with MiscMod, but fixed in MiscMod.

Fixed: https://github.com/cato-a/CoDaM_MiscMod/commit/5e75be370f85cb5ce2a8c012446d105826f37f60

**Closed as completed by cato-a** 2023-01-20 22:32 UTC

**Comment by ghost** [comment] 2023-02-02 10:59
♥️
