### ISSUE TITLE
UNLOCALIZED() / WARNING: Could not translate part of hudelem string: ""

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#1] opened 2023-01-15 05:15 UTC
Hello
After opening the game for the first time (obtained at cod.pm), when I join a server that uses miscmod, some texts are "surrounded/accompanied" by errors/warnings as you can see on the attached screenshot.

![shot0000](https://user-images.githubusercontent.com/55389708/212523987-5baf2af5-0b6c-46da-9aee-043cb431dc49.jpg)

I tried on a public server and on mine (both using 3.0.8 version)
Does someone knows why this is happening ? Do you know how to fix that ?

These errors/warnings do not appear anymore after restarting the game.

**Comment by cato-a** [comment] 2023-01-15 10:38
Hello. I don't think this is a MiscMod issue, it just looks like one because of all the MiscMod hud elements. Like you say the issue is fixed by restarting the game, but you could also do `/vid_restart` in the in-game console to get rid of these `UNLOCALIZED` messages.

I've updated the guide on [cod.pm](https://cod.pm/guide/e981a4/installing-call-of-duty-1-game-client-or-patches) to include the above mentioned fixes for this problem, thanks.

**Closed as completed** 2023-02-15 17:31 UTC
